### ISSUE TITLE
sklearn is deprecated and needs to be replaced with scikit-learn in the setup files.

### ISSUE THREAD

**Issue by tripmat** [Tom-TBT/theonerig#26]
Love you

**Comment by Tom-TBT** [comment]
Good to know. The scikit-learn is already in the [settings](https://github.com/Tom-TBT/theonerig/blob/master/settings.ini) of this repo. 
Maybe the `theonerig_made_worse` isn't your fork name for nothing ;)

**Comment by Tom-TBT** [comment]
my bad. the duplicate sklearn is removed. You can rename your branch to `theonerig_but_better`
